package by.snql.filescanner.ui;

import by.snql.filescanner.model.FileNode;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Comparator;
import java.util.List;

public class PdfReport {

    private static final DateTimeFormatter DATE_FMT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm").withZone(ZoneId.systemDefault());

    private static final float MARGIN = 50;
    private static final float ROW_HEIGHT = 16;
    private static final float HEADER_HEIGHT = 20;

    public static void generate(FileNode root, Path outputFile, int largestLimit) throws IOException {
        try (var doc = new PDDocument()) {
            var font = new PDType1Font(Standard14Fonts.FontName.HELVETICA);
            var boldFont = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
            var monoFont = new PDType1Font(Standard14Fonts.FontName.COURIER);

            var allFiles = FileAnalysis.flattenFiles(root);
            long dirCount = countDirs(root);

            float y = addTitlePage(doc, font, boldFont, root, allFiles.size(), dirCount);

            y = addLargestFiles(doc, font, boldFont, monoFont, root, largestLimit, y);
            addFileTypes(doc, font, boldFont, root, y);

            var groups = FileAnalysis.findDuplicates(root);
            if (!groups.isEmpty()) {
                addDuplicates(doc, font, boldFont, monoFont, groups);
            }

            var emptyDirs = FileAnalysis.findEmptyDirs(root);
            if (!emptyDirs.isEmpty()) {
                addEmptyDirs(doc, font, boldFont, monoFont, emptyDirs);
            }

            addCompression(doc, font, boldFont, root);

            var page = doc.getPage(doc.getNumberOfPages() - 1);
            var stream = new PDPageContentStream(doc, page, PDPageContentStream.AppendMode.APPEND, false);
            stream.setFont(font, 8);
            stream.beginText();
            stream.newLineAtOffset(MARGIN, 20);
            stream.showText("Generated by File Scanner — " + Instant.now().toString().substring(0, 16));
            stream.endText();
            stream.close();

            Files.createDirectories(outputFile.getParent());
            doc.save(outputFile.toFile());
        }
    }

    private static float addTitlePage(PDDocument doc, PDType1Font font, PDType1Font bold,
                                       FileNode root, long fileCount, long dirCount) throws IOException {
        var page = new PDPage(PDRectangle.A4);
        doc.addPage(page);
        var s = new PDPageContentStream(doc, page);

        float w = page.getMediaBox().getWidth();
        float y = page.getMediaBox().getHeight() - MARGIN;

        s.setFont(bold, 24);
        drawText(s, "Disk Usage Report", MARGIN, y);
        y -= 40;

        s.setFont(font, 12);
        drawText(s, "Root: " + root.getPath().toString(), MARGIN, y);
        y -= ROW_HEIGHT;
        drawText(s, "Total size: " + formatSize(root.getSize()), MARGIN, y);
        y -= ROW_HEIGHT;
        drawText(s, "Files: " + formatNum(fileCount) + "    Directories: " + formatNum(dirCount), MARGIN, y);
        y -= ROW_HEIGHT;

        try {
            var store = Files.getFileStore(root.getPath());
            drawText(s, "Disk: " + formatSize(store.getUsableSpace()) + " free of " +
                    formatSize(store.getTotalSpace()), MARGIN, y);
            y -= ROW_HEIGHT;
        } catch (IOException ignored) {}

        drawText(s, "Generated: " + DATE_FMT.format(Instant.now()), MARGIN, y);
        y -= ROW_HEIGHT;

        y -= 30;
        s.setFont(bold, 14);
        drawText(s, "Contents", MARGIN, y);
        y -= 25;

        s.setFont(font, 11);
        String[] toc = {
                "1. Largest Files",
                "2. File Types Breakdown",
                "3. Duplicate Files",
                "4. Empty Directories",
                "5. Compression Estimate"
        };
        for (var line : toc) {
            drawText(s, line, MARGIN + 20, y);
            y -= ROW_HEIGHT;
        }

        s.close();
        return MARGIN;
    }

    private static float addLargestFiles(PDDocument doc, PDType1Font font, PDType1Font bold,
                                          PDType1Font mono, FileNode root, int limit, float startY) throws IOException {
        var files = FileAnalysis.largestFiles(root, limit);
        if (files.isEmpty()) return startY;

        var page = newPage(doc);
        float y = page.getMediaBox().getHeight() - MARGIN;
        float w = page.getMediaBox().getWidth();
        float colName = w - MARGIN * 2 - 100;

        var s = new PDPageContentStream(doc, page);

        s.setFont(bold, 16);
        drawText(s, "Largest " + files.size() + " Files", MARGIN, y);
        y -= HEADER_HEIGHT + 5;

        s.setFont(bold, 9);
        float[] cols = {MARGIN, MARGIN + 30, MARGIN + colName + 5};
        drawText(s, "#", cols[0], y);
        drawText(s, "Size", cols[1], y);
        drawText(s, "Path", cols[2], y);
        y -= HEADER_HEIGHT;
        drawLine(s, MARGIN, y, w - MARGIN, y);
        y -= 2;

        s.setFont(mono, 8);
        int i = 1;
        for (var f : files) {
            if (y < MARGIN + ROW_HEIGHT) {
                s.close();
                page = newPage(doc);
                y = page.getMediaBox().getHeight() - MARGIN;
                s = new PDPageContentStream(doc, page);
                s.setFont(mono, 8);
            }
            drawText(s, String.valueOf(i++), cols[0], y);
            drawText(s, formatSize(f.getSize()), cols[1], y);
            String path = f.getPath().toString();
            if (path.length() > 90) path = "…" + path.substring(path.length() - 89);
            drawText(s, path, cols[2], y);
            y -= ROW_HEIGHT;
        }
        s.close();
        return y;
    }

    private static void addFileTypes(PDDocument doc, PDType1Font font, PDType1Font bold,
                                      FileNode root, float startY) throws IOException {
        var map = FileAnalysis.fileTypeBreakdown(root);
        var sorted = map.values().stream()
                .sorted(Comparator.comparingLong(FileAnalysis.FileTypeStat::getTotalSize).reversed())
                .toList();
        if (sorted.isEmpty()) return;

        var page = ensurePage(doc, startY, 80);
        float y;
        var s = new PDPageContentStream(doc, page, PDPageContentStream.AppendMode.APPEND, false);
        y = startAt(page, startY, MARGIN);

        s.setFont(bold, 16);
        drawText(s, "File Types", MARGIN, y);
        y -= HEADER_HEIGHT + 5;

        s.setFont(bold, 9);
        float[] cols = {MARGIN, MARGIN + 130, MARGIN + 200, MARGIN + 300};
        drawText(s, "Extension", cols[0], y);
        drawText(s, "Files", cols[1], y);
        drawText(s, "Total Size", cols[2], y);
        drawText(s, "Share", cols[3], y);
        y -= HEADER_HEIGHT;
        drawLine(s, MARGIN, y, page.getMediaBox().getWidth() - MARGIN, y);
        y -= 2;

        s.setFont(font, 9);
        long total = sorted.stream().mapToLong(FileAnalysis.FileTypeStat::getTotalSize).sum();
        for (var st : sorted) {
            if (y < MARGIN) { s.close(); page = newPage(doc); y = freshY(page); s = resumeStream(doc, page); s.setFont(font, 9); }
            double pct = total > 0 ? (double) st.getTotalSize() / total * 100 : 0;
            drawText(s, st.getExtension(), cols[0], y);
            drawText(s, formatNum(st.getCount()), cols[1], y);
            drawText(s, formatSize(st.getTotalSize()), cols[2], y);
            drawText(s, String.format("%.1f%%", pct), cols[3], y);
            y -= ROW_HEIGHT;
        }
        s.close();
    }

    private static void addDuplicates(PDDocument doc, PDType1Font font, PDType1Font bold,
                                       PDType1Font mono, List<FileAnalysis.DuplicateGroup> groups) throws IOException {
        var page = newPage(doc);
        float y = page.getMediaBox().getHeight() - MARGIN;
        var s = new PDPageContentStream(doc, page);

        s.setFont(bold, 16);
        long waste = FileAnalysis.totalDuplicateWaste(groups);
        drawText(s, "Duplicates (showing top " + groups.size() + " groups, waste: " +
                formatSize(waste) + ")", MARGIN, y);
        y -= HEADER_HEIGHT + 5;
        s.setFont(font, 8);
        drawText(s, "Excludes: .git/, node_modules/, target/, __pycache__/, build/, dist/, vendor/, .venv/",
                MARGIN, y);
        y -= HEADER_HEIGHT;

        s.setFont(mono, 8);
        for (var g : groups) {
            if (y < MARGIN + 60) { s.close(); page = newPage(doc); y = freshY(page); s = resumeStream(doc, page); s.setFont(mono, 8); }

            String prefix = FileAnalysis.commonPathPrefix(g.files);
            s.setFont(bold, 9);
            drawText(s, g.files.size() + " files × " + formatSize(g.fileSize) +
                    " each (waste: " + formatSize(g.wastedSize()) + ")", MARGIN, y);
            y -= ROW_HEIGHT;
            if (!prefix.isEmpty()) {
                s.setFont(font, 7);
                drawText(s, "  in " + prefix, MARGIN + 5, y);
                y -= 12;
            }
            s.setFont(mono, 8);
            int shown = 0;
            for (var f : g.files) {
                if (shown++ >= 3) break;
                drawText(s, "  " + f.getPath().toString(), MARGIN + 10, y);
                y -= 12;
            }
            if (g.files.size() > 3) {
                drawText(s, "  ... and " + (g.files.size() - 3) + " more files", MARGIN + 10, y);
                y -= 12;
            }
            y -= 4;
        }
        s.close();
    }

    private static void addEmptyDirs(PDDocument doc, PDType1Font font, PDType1Font bold,
                                      PDType1Font mono, List<FileNode> dirs) throws IOException {
        var page = ensurePage(doc, MARGIN, 80);
        var s = new PDPageContentStream(doc, page, PDPageContentStream.AppendMode.APPEND, false);
        float y = startAt(page, freshY(page), MARGIN);

        s.setFont(bold, 16);
        drawText(s, "Empty Directories (" + dirs.size() + ")", MARGIN, y);
        y -= HEADER_HEIGHT + 5;

        s.setFont(mono, 8);
        for (var d : dirs) {
            if (y < MARGIN) { s.close(); page = newPage(doc); y = freshY(page); s = resumeStream(doc, page); s.setFont(mono, 8); }
            drawText(s, d.getPath().toString(), MARGIN + 5, y);
            y -= 12;
        }
        s.close();
    }

    private static void addCompression(PDDocument doc, PDType1Font font, PDType1Font bold,
                                        FileNode root) throws IOException {
        var estimate = CompressionEstimate.estimate(root);
        var page = newPage(doc);
        float y = page.getMediaBox().getHeight() - MARGIN;
        float w = page.getMediaBox().getWidth();
        var s = new PDPageContentStream(doc, page);

        s.setFont(bold, 16);
        drawText(s, "Compression Estimate", MARGIN, y);
        y -= HEADER_HEIGHT + 5;

        s.setFont(font, 10);
        drawText(s, "Original:           " + formatSize(estimate.originalSize()), MARGIN + 10, y);
        y -= ROW_HEIGHT;
        drawText(s, "Est. compressed:    " + formatSize(estimate.estimatedCompressed()), MARGIN + 10, y);
        y -= ROW_HEIGHT;
        drawText(s, "Could save:         " + formatSize(estimate.savings()) +
                " (" + String.format("%.0f%%", (1 - estimate.ratio()) * 100) + ")", MARGIN + 10, y);
        y -= ROW_HEIGHT + 15;

        s.setFont(bold, 9);
        float[] cols = {MARGIN, MARGIN + 140, MARGIN + 260, MARGIN + 380};
        drawText(s, "Category", cols[0], y);
        drawText(s, "Original", cols[1], y);
        drawText(s, "Compressed", cols[2], y);
        drawText(s, "Savings", cols[3], y);
        y -= HEADER_HEIGHT;
        drawLine(s, MARGIN, y, w - MARGIN, y);
        y -= 2;

        var allFiles = FileAnalysis.flattenFiles(root);
        var byCat = new java.util.LinkedHashMap<String, long[]>();
        for (var f : allFiles) {
            String cat = catName(f.getName());
            var arr = byCat.computeIfAbsent(cat, k -> new long[2]);
            arr[0] += f.getSize();
            arr[1] += CompressionEstimate.estimateCompressedSize(f);
        }

        s.setFont(font, 9);
        for (var entry : byCat.entrySet().stream()
                .sorted((a, b) -> Long.compare(b.getValue()[1], a.getValue()[1])).toList()) {
            long orig = entry.getValue()[0], comp = entry.getValue()[1], save = orig - comp;
            drawText(s, entry.getKey(), cols[0], y);
            drawText(s, formatSize(orig), cols[1], y);
            drawText(s, formatSize(comp), cols[2], y);
            drawText(s, formatSize(save), cols[3], y);
            y -= ROW_HEIGHT;
        }
        s.close();
    }

    private static String catName(String name) {
        String ext = ext(name);
        return switch (ext) {
            case "jpg", "jpeg", "png", "gif", "bmp", "svg", "webp", "ico", "tiff", "psd", "raw" -> "Image";
            case "mp4", "mkv", "avi", "mov", "wmv", "flv", "webm" -> "Video";
            case "mp3", "wav", "flac", "aac", "ogg", "wma", "m4a", "opus" -> "Audio";
            case "pdf", "doc", "docx", "xls", "xlsx", "ppt", "pptx", "odt" -> "Document";
            case "zip", "tar", "gz", "bz2", "xz", "7z", "rar", "jar", "war", "iso" -> "Archive";
            case "java", "py", "js", "ts", "c", "cpp", "h", "hpp", "cs", "go", "rs", "rb", "php",
                 "swift", "kt", "scala", "sh", "html", "css", "xml", "json" -> "Code";
            case "exe", "dll", "so", "dylib", "bin" -> "Executable";
            default -> "Other";
        };
    }

    private static String ext(String name) {
        int dot = name.lastIndexOf('.');
        return dot > 0 ? name.substring(dot + 1).toLowerCase() : "";
    }

    private static long countDirs(FileNode node) {
        long count = node.isDirectory() ? 1 : 0;
        for (var child : node.getChildren()) count += countDirs(child);
        return count;
    }

    private static PDPage ensurePage(PDDocument doc, float y, float margin) {
        if (y < margin) {
            var page = newPage(doc);
            return page;
        }
        return doc.getPage(doc.getNumberOfPages() - 1);
    }

    private static float startAt(PDPage page, float y, float margin) {
        if (y < margin + 60) return freshY(page);
        return y - 20;
    }

    private static float freshY(PDPage page) {
        return page.getMediaBox().getHeight() - MARGIN;
    }

    private static PDPage newPage(PDDocument doc) {
        var page = new PDPage(PDRectangle.A4);
        doc.addPage(page);
        return page;
    }

    private static PDPageContentStream resumeStream(PDDocument doc, PDPage page) throws IOException {
        return new PDPageContentStream(doc, page, PDPageContentStream.AppendMode.APPEND, false);
    }

    private static void drawText(PDPageContentStream s, String text, float x, float y) throws IOException {
        s.beginText();
        s.newLineAtOffset(x, y);
        s.showText(asciiSafe(text));
        s.endText();
    }

    private static void drawLine(PDPageContentStream s, float x1, float y, float x2, float y2) throws IOException {
        s.setLineWidth(0.5f);
        s.moveTo(x1, y);
        s.lineTo(x2, y2);
        s.stroke();
    }

    private static String formatNum(long n) {
        return String.format("%,d", n);
    }

    private static final String[] SIZE_UNITS = {"B", "KB", "MB", "GB", "TB"};

    private static String formatSize(long bytes) {
        if (bytes <= 0) return "0 B";
        int unit = (int) (Math.log10(bytes) / Math.log10(1024));
        unit = Math.min(unit, SIZE_UNITS.length - 1);
        double value = bytes / Math.pow(1024, unit);
        return String.format("%.1f %s", value, SIZE_UNITS[unit]);
    }

    private static String asciiSafe(String s) {
        var sb = new StringBuilder(s.length());
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            sb.append(c < 128 ? c : (c < 256 ? c : '?'));
        }
        return sb.toString();
    }
}
