package by.snql.filescanner.ui;

import by.snql.filescanner.model.FileNode;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;

import java.awt.Color;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

public class PdfReport {

    private static final DateTimeFormatter DATE_FMT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm").withZone(ZoneId.systemDefault());

    private static final float MARGIN = 50;
    private static final float ROW_HEIGHT = 14;
    private static final float HEADER_HEIGHT = 20;

    private static final Color[] PIE_COLORS = {
            new Color(0x34, 0x98, 0xDB), new Color(0x2E, 0xCC, 0x71),
            new Color(0xE7, 0x4C, 0x3C), new Color(0x9B, 0x59, 0xB6),
            new Color(0xF3, 0x9C, 0x12), new Color(0x1A, 0xBC, 0x9C),
            new Color(0xE6, 0x7E, 0x22), new Color(0x95, 0xA5, 0xA6)
    };

    public static void generate(FileNode root, Path outputFile, int largestLimit) throws IOException {
        try (var doc = new PDDocument()) {
            var font = new PDType1Font(Standard14Fonts.FontName.HELVETICA);
            var boldFont = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
            var monoFont = new PDType1Font(Standard14Fonts.FontName.COURIER);

            var allFiles = FileAnalysis.flattenFiles(root);
            long dirCount = countDirs(root);

            addTitlePage(doc, font, boldFont, root, allFiles.size(), dirCount);
            addLargestFiles(doc, font, boldFont, monoFont, root, largestLimit);
            addFileTypes(doc, font, boldFont, monoFont, root);
            addDuplicatesSection(doc, font, boldFont, monoFont, root);

            var emptyDirs = FileAnalysis.findEmptyDirs(root);
            if (!emptyDirs.isEmpty()) {
                addEmptyDirs(doc, font, boldFont, monoFont, emptyDirs);
            }

            addCompression(doc, font, boldFont, root);

            var page = doc.getPage(doc.getNumberOfPages() - 1);
            var stream = new PDPageContentStream(doc, page, PDPageContentStream.AppendMode.APPEND, false);
            stream.setFont(font, 8);
            stream.beginText();
            stream.newLineAtOffset(MARGIN, 20);
            stream.showText("Generated by File Scanner  |  github.com/ruslansin/file-scanner");
            stream.endText();
            stream.close();

            Files.createDirectories(outputFile.getParent());
            doc.save(outputFile.toFile());
        }
    }

    // ── Title ──

    private static void addTitlePage(PDDocument doc, PDType1Font font, PDType1Font bold,
                                      FileNode root, long fileCount, long dirCount) throws IOException {
        var page = newPage(doc);
        var s = new PDPageContentStream(doc, page);
        float y = freshY(page);

        s.setFont(bold, 24);
        drawText(s, "Disk Usage Report", MARGIN, y);
        y -= 36;

        s.setFont(font, 11);
        drawText(s, "Root:        " + root.getPath().toString(), MARGIN, y); y -= ROW_HEIGHT;
        drawText(s, "Total size:  " + formatSize(root.getSize()), MARGIN, y); y -= ROW_HEIGHT;
        drawText(s, "Files:       " + formatNum(fileCount) + "    Directories: " + formatNum(dirCount), MARGIN, y); y -= ROW_HEIGHT;

        try {
            var store = Files.getFileStore(root.getPath());
            drawText(s, "Disk free:   " + formatSize(store.getUsableSpace()) + " of " +
                    formatSize(store.getTotalSpace()), MARGIN, y); y -= ROW_HEIGHT;
        } catch (IOException ignored) {}

        drawText(s, "Generated:   " + DATE_FMT.format(Instant.now()), MARGIN, y);
        y -= 30;

        s.setFont(bold, 14);
        drawText(s, "Contents", MARGIN, y);
        y -= 22;
        s.setFont(font, 11);
        for (var line : List.of("1. Largest Files", "2. File Types", "3. Duplicates",
                "4. Empty Directories", "5. Compression Estimate")) {
            drawText(s, "    " + line, MARGIN, y);
            y -= ROW_HEIGHT;
        }
        s.close();
    }

    // ── Largest Files ──

    private static void addLargestFiles(PDDocument doc, PDType1Font font, PDType1Font bold,
                                         PDType1Font mono, FileNode root, int limit) throws IOException {
        var files = FileAnalysis.largestFiles(root, limit);
        if (files.isEmpty()) return;

        var page = newPage(doc);
        float y = freshY(page);
        var s = new PDPageContentStream(doc, page);

        s.setFont(bold, 16);
        drawText(s, "Largest " + files.size() + " Files", MARGIN, y);
        y -= HEADER_HEIGHT + 4;

        float colSize = MARGIN + 28;
        float colPath = MARGIN + 105;
        s.setFont(bold, 9);
        drawText(s, "#", MARGIN, y);
        drawText(s, "Size", colSize, y);
        drawText(s, "Path", colPath, y);
        y -= HEADER_HEIGHT;
        drawLine(s, MARGIN, y, page.getMediaBox().getWidth() - MARGIN, y);
        y -= 3;

        s.setFont(mono, 8);
        int i = 1;
        for (var f : files) {
            if (y < MARGIN + ROW_HEIGHT) { s.close(); page = newPage(doc); y = freshY(page); s = resumeStream(doc, page); s.setFont(mono, 8); }
            drawText(s, padLeft(String.valueOf(i++), 2), MARGIN, y);
            drawText(s, padLeft(formatSize(f.getSize()), 10), colSize, y);
            String path = f.getPath().toString();
            if (path.length() > 100) path = "…" + path.substring(path.length() - 99);
            drawText(s, path, colPath, y);
            y -= ROW_HEIGHT;
        }
        s.close();
    }

    // ── File Types (table + pie chart) ──

    private static void addFileTypes(PDDocument doc, PDType1Font font, PDType1Font bold,
                                      PDType1Font mono, FileNode root) throws IOException {
        var map = FileAnalysis.fileTypeBreakdown(root);
        var sorted = map.values().stream()
                .sorted(Comparator.comparingLong(FileAnalysis.FileTypeStat::getTotalSize).reversed())
                .toList();
        if (sorted.isEmpty()) return;

        var page = newPage(doc);
        float w = page.getMediaBox().getWidth();
        float y = freshY(page);
        var s = new PDPageContentStream(doc, page);

        s.setFont(bold, 16);
        drawText(s, "File Types", MARGIN, y);
        y -= HEADER_HEIGHT + 4;

        drawPieChart(s, sorted, w - MARGIN - 130, y - 120, 120);

        float[] cols = {MARGIN, MARGIN + 100, MARGIN + 165, MARGIN + 250};
        s.setFont(bold, 9);
        drawText(s, "Extension", cols[0], y);
        drawText(s, "Files", cols[1], y);
        drawText(s, "Size", cols[2], y);
        drawText(s, "Share", cols[3], y);
        y -= HEADER_HEIGHT;
        drawLine(s, MARGIN, y, w - MARGIN - 140, y);
        y -= 2;

        s.setFont(font, 9);
        long total = sorted.stream().mapToLong(FileAnalysis.FileTypeStat::getTotalSize).sum();
        for (var st : sorted) {
            if (y < MARGIN) { s.close(); page = newPage(doc); y = freshY(page); s = resumeStream(doc, page); s.setFont(font, 9); }
            double pct = total > 0 ? (double) st.getTotalSize() / total * 100 : 0;
            drawText(s, st.getExtension(), cols[0], y);
            drawText(s, formatNum(st.getCount()), cols[1], y);
            drawText(s, formatSize(st.getTotalSize()), cols[2], y);
            drawText(s, String.format("%.1f%%", pct), cols[3], y);
            y -= ROW_HEIGHT;
        }
        s.close();
    }

    private static void drawPieChart(PDPageContentStream s,
                                      List<FileAnalysis.FileTypeStat> sorted,
                                      float cx, float cy, float radius) throws IOException {
        long total = sorted.stream().mapToLong(FileAnalysis.FileTypeStat::getTotalSize).sum();
        if (total == 0) return;

        int count = Math.min(sorted.size(), 7);
        double angle = 90;
        for (int i = 0; i < count; i++) {
            double sweep = (double) sorted.get(i).getTotalSize() / total * 360;
            if (sweep < 2) break;

            Color color = PIE_COLORS[i % PIE_COLORS.length];
            s.setNonStrokingColor(color.getRed() / 255f, color.getGreen() / 255f, color.getBlue() / 255f);
            s.setStrokingColor(1, 1, 1);
            s.setLineWidth(0.5f);
            drawArc(s, cx, cy, radius, angle, sweep);
            angle += sweep;
        }
        if (count < sorted.size()) {
            double remaining = 360 - (angle - 90);
            if (remaining > 2) {
                s.setNonStrokingColor(0.58f, 0.65f, 0.65f);
                drawArc(s, cx, cy, radius, angle, remaining);
            }
        }
        s.setNonStrokingColor(1, 1, 1);
        float holeR = radius * 0.4f;
        float k = 0.5522847498f * holeR;
        s.moveTo(cx + holeR, cy);
        s.curveTo(cx + holeR, cy - k, cx + k, cy - holeR, cx, cy - holeR);
        s.curveTo(cx - k, cy - holeR, cx - holeR, cy - k, cx - holeR, cy);
        s.curveTo(cx - holeR, cy + k, cx - k, cy + holeR, cx, cy + holeR);
        s.curveTo(cx + k, cy + holeR, cx + holeR, cy + k, cx + holeR, cy);
        s.fill();

        float legendX = cx + radius + 20;
        float legendY = cy + radius - 15;
        s.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 8);
        for (int i = 0; i < count; i++) {
            var st = sorted.get(i);
            double pct = (double) st.getTotalSize() / total * 100;
            if (pct < 1) break;
            Color color = PIE_COLORS[i % PIE_COLORS.length];
            s.setNonStrokingColor(color.getRed() / 255f, color.getGreen() / 255f, color.getBlue() / 255f);
            s.addRect(legendX, legendY - 6, 10, 10);
            s.fill();
            s.setNonStrokingColor(0, 0, 0);
            drawText(s, st.getExtension() + " " + String.format("%.1f%%", pct), legendX + 14, legendY);
            legendY -= 16;
        }
    }

    private static void drawArc(PDPageContentStream s, float cx, float cy, float r,
                                 double startAngle, double sweep) throws IOException {
        double startRad = Math.toRadians(startAngle);
        double endRad = Math.toRadians(startAngle + sweep);
        float x1 = (float)(cx + r * Math.cos(startRad));
        float y1 = (float)(cy - r * Math.sin(startRad));
        float xc = (float)(cx + r * 1.5 * Math.cos(Math.toRadians(startAngle + sweep / 2)));
        float yc = (float)(cy - r * 1.5 * Math.sin(Math.toRadians(startAngle + sweep / 2)));
        float x2 = (float)(cx + r * Math.cos(endRad));
        float y2 = (float)(cy - r * Math.sin(endRad));

        s.moveTo(cx, cy);
        s.lineTo(x1, y1);
        s.curveTo(xc, yc, xc, yc, x2, y2);
        s.lineTo(cx, cy);
        s.fill();
        s.stroke();
    }

    // ── Duplicates ──

    private static void addDuplicatesSection(PDDocument doc, PDType1Font font, PDType1Font bold,
                                              PDType1Font mono, FileNode root) throws IOException {
        if (!Settings.get().duplicateSHA256) {
            var page = newPage(doc);
            var s = new PDPageContentStream(doc, page);
            float y = freshY(page);

            s.setFont(bold, 16);
            drawText(s, "Duplicates", MARGIN, y);
            y -= HEADER_HEIGHT + 5;
            s.setFont(font, 11);
            drawText(s, "Duplicate detection is disabled because SHA-256 hashing is off (default).", MARGIN, y);
            y -= ROW_HEIGHT;
            drawText(s, "Scanning every file byte-by-byte is accurate but slow on large directories.", MARGIN, y);
            y -= ROW_HEIGHT;
            s.setFont(bold, 11);
            drawText(s, "To enable: open Settings (gear icon), check 'SHA-256 duplicate detection'.", MARGIN, y);
            s.close();
            return;
        }

        var groups = FileAnalysis.findDuplicates(root);
        if (groups.isEmpty()) return;

        var page = newPage(doc);
        float y = freshY(page);
        var s = new PDPageContentStream(doc, page);

        s.setFont(bold, 16);
        long waste = FileAnalysis.totalDuplicateWaste(groups);
        drawText(s, "Duplicates", MARGIN, y);
        y -= HEADER_HEIGHT + 2;
        s.setFont(font, 10);
        drawText(s, "Showing top " + groups.size() + " groups, total waste: " + formatSize(waste), MARGIN, y);
        y -= ROW_HEIGHT;
        drawText(s, "Excludes: .git/, node_modules/, target/, __pycache__/, build/, dist/, vendor/", MARGIN, y);
        y -= HEADER_HEIGHT;

        for (var g : groups) {
            if (y < MARGIN + 50) { s.close(); page = newPage(doc); y = freshY(page); s = resumeStream(doc, page); }

            s.setFont(bold, 9);
            String prefix = FileAnalysis.commonPathPrefix(g.files);
            drawText(s, g.files.size() + " files  x  " + formatSize(g.fileSize) +
                    "       waste: " + formatSize(g.wastedSize()), MARGIN, y);
            y -= ROW_HEIGHT;
            if (!prefix.isEmpty()) {
                s.setFont(font, 7);
                drawText(s, "  " + prefix, MARGIN + 5, y);
                y -= 12;
            }
            s.setFont(mono, 7);
            int shown = 0;
            for (var f : g.files) {
                if (shown++ >= 3) break;
                drawText(s, "  " + f.getPath().toString(), MARGIN + 8, y);
                y -= 11;
            }
            if (g.files.size() > 3) {
                drawText(s, "  ... and " + (g.files.size() - 3) + " more", MARGIN + 8, y);
                y -= 11;
            }
            y -= 4;
        }
        s.close();
    }

    // ── Empty Dirs ──

    private static void addEmptyDirs(PDDocument doc, PDType1Font font, PDType1Font bold,
                                      PDType1Font mono, List<FileNode> dirs) throws IOException {
        var page = newPage(doc);
        float y = freshY(page);
        var s = new PDPageContentStream(doc, page);

        s.setFont(bold, 16);
        drawText(s, "Empty Directories (" + dirs.size() + ")", MARGIN, y);
        y -= HEADER_HEIGHT + 4;

        s.setFont(mono, 8);
        for (var d : dirs) {
            if (y < MARGIN) { s.close(); page = newPage(doc); y = freshY(page); s = resumeStream(doc, page); s.setFont(mono, 8); }
            drawText(s, d.getPath().toString(), MARGIN + 5, y);
            y -= 12;
        }
        s.close();
    }

    // ── Compression ──

    private static void addCompression(PDDocument doc, PDType1Font font, PDType1Font bold,
                                        FileNode root) throws IOException {
        var estimate = CompressionEstimate.estimate(root);
        var page = newPage(doc);
        float y = freshY(page);
        float w = page.getMediaBox().getWidth();
        var s = new PDPageContentStream(doc, page);

        s.setFont(bold, 16);
        drawText(s, "Compression Estimate", MARGIN, y);
        y -= HEADER_HEIGHT + 4;

        s.setFont(font, 10);
        drawText(s, "Original:           " + formatSize(estimate.originalSize()), MARGIN + 10, y); y -= ROW_HEIGHT;
        drawText(s, "Est. compressed:    " + formatSize(estimate.estimatedCompressed()), MARGIN + 10, y); y -= ROW_HEIGHT;
        drawText(s, "Could save:         " + formatSize(estimate.savings()) +
                " (" + String.format("%.0f%%", (1 - estimate.ratio()) * 100) + ")", MARGIN + 10, y);
        y -= ROW_HEIGHT + 10;

        float[] cols = {MARGIN, MARGIN + 140, MARGIN + 260, MARGIN + 380};
        s.setFont(bold, 9);
        drawText(s, "Category", cols[0], y);
        drawText(s, "Original", cols[1], y);
        drawText(s, "Compressed", cols[2], y);
        drawText(s, "Savings", cols[3], y);
        y -= HEADER_HEIGHT;
        drawLine(s, MARGIN, y, w - MARGIN, y);
        y -= 2;

        var allFiles = FileAnalysis.flattenFiles(root);
        var byCat = new java.util.LinkedHashMap<String, long[]>();
        for (var f : allFiles) {
            String cat = catName(f.getName());
            var arr = byCat.computeIfAbsent(cat, k -> new long[2]);
            arr[0] += f.getSize();
            arr[1] += CompressionEstimate.estimateCompressedSize(f);
        }

        s.setFont(font, 9);
        for (var entry : byCat.entrySet().stream()
                .sorted((a, b) -> Long.compare(b.getValue()[1], a.getValue()[1])).toList()) {
            long orig = entry.getValue()[0], comp = entry.getValue()[1], save = orig - comp;
            drawText(s, entry.getKey(), cols[0], y);
            drawText(s, formatSize(orig), cols[1], y);
            drawText(s, formatSize(comp), cols[2], y);
            drawText(s, formatSize(save), cols[3], y);
            y -= ROW_HEIGHT;
        }
        s.close();
    }

    // ── Helpers ──

    private static String catName(String name) {
        String ext = ext(name);
        return switch (ext) {
            case "jpg", "jpeg", "png", "gif", "bmp", "svg", "webp", "ico", "tiff", "psd", "raw" -> "Image";
            case "mp4", "mkv", "avi", "mov", "wmv", "flv", "webm" -> "Video";
            case "mp3", "wav", "flac", "aac", "ogg", "wma", "m4a", "opus" -> "Audio";
            case "pdf", "doc", "docx", "xls", "xlsx", "ppt", "pptx", "odt" -> "Document";
            case "zip", "tar", "gz", "bz2", "xz", "7z", "rar", "jar", "war", "iso" -> "Archive";
            case "java", "py", "js", "ts", "c", "cpp", "h", "hpp", "cs", "go", "rs", "rb", "php",
                 "swift", "kt", "scala", "sh", "html", "css", "xml", "json" -> "Code";
            case "exe", "dll", "so", "dylib", "bin" -> "Executable";
            default -> "Other";
        };
    }

    private static String ext(String name) {
        int dot = name.lastIndexOf('.');
        return dot > 0 ? name.substring(dot + 1).toLowerCase() : "";
    }

    private static long countDirs(FileNode node) {
        long count = node.isDirectory() ? 1 : 0;
        for (var child : node.getChildren()) count += countDirs(child);
        return count;
    }

    private static PDPage newPage(PDDocument doc) {
        var page = new PDPage(PDRectangle.A4);
        doc.addPage(page);
        return page;
    }

    private static float freshY(PDPage page) {
        return page.getMediaBox().getHeight() - MARGIN;
    }

    private static PDPageContentStream resumeStream(PDDocument doc, PDPage page) throws IOException {
        return new PDPageContentStream(doc, page, PDPageContentStream.AppendMode.APPEND, false);
    }

    private static void drawText(PDPageContentStream s, String text, float x, float y) throws IOException {
        s.beginText();
        s.newLineAtOffset(x, y);
        s.showText(asciiSafe(text));
        s.endText();
    }

    private static void drawLine(PDPageContentStream s, float x1, float y, float x2, float y2) throws IOException {
        s.setLineWidth(0.5f);
        s.setStrokingColor(0.7f, 0.7f, 0.7f);
        s.moveTo(x1, y);
        s.lineTo(x2, y2);
        s.stroke();
        s.setStrokingColor(0, 0, 0);
    }

    private static String padLeft(String s, int len) {
        return s.length() >= len ? s : " ".repeat(len - s.length()) + s;
    }

    private static String formatNum(long n) {
        return String.format("%,d", n);
    }

    private static final String[] SIZE_UNITS = {"B", "KB", "MB", "GB", "TB"};

    private static String formatSize(long bytes) {
        if (bytes <= 0) return "0 B";
        int unit = (int) (Math.log10(bytes) / Math.log10(1024));
        unit = Math.min(unit, SIZE_UNITS.length - 1);
        double value = bytes / Math.pow(1024, unit);
        return String.format("%.1f %s", value, SIZE_UNITS[unit]);
    }

    private static String asciiSafe(String s) {
        var sb = new StringBuilder(s.length());
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            sb.append(c < 128 ? c : (c < 256 ? c : '?'));
        }
        return sb.toString();
    }
}
